import {
  ChatInputCommandInteraction,
  GuildChannel,
  MessageFlags,
} from 'discord.js'
import { moderationMessages } from '../../../config/moderationMessages'
import { calculateExpiryDate } from 'utils/calculateExpiryDate'
import { strikeUtils } from 'utils/queryDB'
import { client } from '../../../client'
import {
  createEmbedType,
  formatEmbedField,
  logStrike,
} from '../../../utils/logCommandUse'
import { sendDm } from '../../../utils/sendDm'
import { formatDiscordDate, getGuildDisplayName } from './moderationLogUtils'

export default {
  async execute(interaction: ChatInputCommandInteraction) {
    try {
      await interaction.deferReply()
      const discordChannel = interaction.channel
      const user = interaction.options.getUser('user', true)
      let amount = interaction.options.getInteger('strikes', true)
      const reason =
        interaction.options.getString('reason', false) || 'No reason provided'
      const reference =
        interaction.options.getChannel('reference channel', false) ||
        discordChannel
      const referenceChannelId = reference?.id || '69' // this needs to be a number in the string so the channel appears as 'unknown' if not found

      const expiryDate = await calculateExpiryDate(user.id) // crude function to determine expiry length of strike

      const hasStrikes: boolean = await strikeUtils.checkForInstances(user.id)
      if (hasStrikes && amount === 0) amount = 1

      const username = (await client.users.fetch(user.id)).username
      const blame = await getGuildDisplayName(
        interaction.guild,
        interaction.user.id,
        interaction.user.username,
      )
      const referenceChannel: GuildChannel = (await client.channels.fetch(
        referenceChannelId,
      )) as GuildChannel
      const reasonFormat = formatEmbedField(reason)
      const strikeExpiry =
        expiryDate || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)

      const strikeId = await strikeUtils.addStrike({
        id: 0, // This will be auto-generated by the database
        user_id: user.id,
        reason: reason,
        issued_by_id: interaction.user.id,
        issued_at: new Date(),
        expires_at: strikeExpiry,
        amount: amount,
        reference: referenceChannel.name ?? 'unknown channel',
      })

      const strikeList = await strikeUtils.getUserStrikes(user.id)
      const totalStrikes = strikeList.reduce(
        (acc: any, strike: any) => acc + strike.amount,
        0,
      )

      // log usage
      const embed = createEmbedType(
        'STRIKE ADDED',
        `<@${user.id}>`,
        16711680,
        [
          {
            name: `Strike`,
            value: `#${strikeId}`,
            inline: true,
          },
          {
            name: `Amount`,
            value: `${amount}`,
            inline: true,
          },
          {
            name: `Total`,
            value: `${totalStrikes}`,
            inline: true,
          },
          { name: `Reason`, value: `${reasonFormat}`, inline: false },
          {
            name: `Reference`,
            value: referenceChannel.name ?? 'unknown channel',
            inline: true,
          },
          {
            name: `Expires`,
            value: formatDiscordDate(strikeExpiry),
            inline: true,
          },
        ],
        null,
        `${blame}`,
      )
      await logStrike('add_strike', embed)

      await sendDm(
        user.id,
        moderationMessages.strikeDm({ amount, reason, totalStrikes }),
      )

      await interaction.editReply(
        `User ${username} given ${amount} strikes ${reason == 'No reason provided' ? `for ${reason}` : ``} (total: ${totalStrikes})`,
      )
    } catch (err: any) {
      console.error(err)
    }
  },
}
